### ISSUE TITLE
Doesn't include 'font-display: swap' for Google Fonts link

### ISSUE THREAD

**Issue by ConnorVO** [Tom-Bonnike/netlify-plugin-inline-source#10]
NOt sure if this is outside the scope of what this plugin is used for, but I am using it for my fonts from Google and it doesn't include the `font-display: swap` attribute in the inline style

**Comment by Tom-Bonnike** [comment]
If you’re sure you’re using the `?display=swap` query param in the google fonts URL, from its code it seems like [`inline-source`](https://github.com/popeindustries/inline-source) strips query params when loading remote sources…
https://github.com/popeindustries/inline-source/blob/020f156468432aaca5f698203006d10768c00a73/lib/utils.js#L165-L166

Can you open an issue there, please? :) This plugin is simply calling `inline-source` so the change should be done there.
