### ISSUE TITLE
Unable to get svg inlined with Hugo

### ISSUE THREAD

**Issue by TonioGela** [Tom-Bonnike/netlify-plugin-inline-source#12]
Hello, I'm trying to inline the svgs [on this site](https://dashboard.toniogela.dev/) that is build using Hugo.
I noticed that hugo while building replaces the `inline` attribute name with attrivute name + attribute definition (i.e. `inline=""`) which I thought it may be a issue but apparently on others sites I build with this plugin it's not (at least for non-svg files since I haven't tested with other svgs)
I tried removing every other plugin on netlify, disabling the Netlify built in optimizations and tested the plugin even locally but without success.
A thing to notice is that for now (since I'm testing it) I left a `<link rel="preload" as="image" href="foo.svg">` in the `head` which is clearly a non-sense, can this cause issues?

**Comment by Tom-Bonnike** [comment]
Heya. Could you maybe make the site’s repository public so I can take a look at the exact setup?

> I tried removing every other plugin on netlify, disabling the Netlify built in optimizations and tested the plugin even locally but without success.

Cool, that’s what I would have suggested.

---

Did you use the `svgAsImage` option? `inline-source` doesn’t inline SVGs by default.

**Comment by Tom-Bonnike** [comment]
Heya. Could you maybe make the site’s repository public so I can take a look at the exact setup? I’m not sure, that `inline=""` could indeed be the problem tbh. Maybe try setting a value like `inline="true"` or `inline="inline"`?
Just to be sure… you’re not using the `svgAsImage` option, are you?

> I tried removing every other plugin on netlify, disabling the Netlify built in optimizations and tested the plugin even locally but without success.

Cool, that’s what I would have suggested.

> A thing to notice is that for now (since I'm testing it) I left a <link rel="preload" as="image" href="foo.svg"> in the head which is clearly a non-sense, can this cause issues?

If you manage to get them inlined you should probably remove that yeah!

---

Btw you may want to consider simply using Hugo’s templating language to inline your svgs? From a quick search it seems like you can render the svg files directly as partials? Also quick warning, sometimes SVGs are so big that it may lead to worse performance to inline them.

**Comment by TonioGela** [comment]
> Heya. Could you maybe make the site’s repository public so I can take a look at the exact setup? I’m not sure, that `inline=""` could indeed be the problem tbh. Maybe try setting a value like `inline="true"` or `inline="inline"`?

Argh, no luck, still not included with both `inline="true"` and `inline="inline"`. I made the repo public [here](https://github.com/TonioGela/dashboard) (thanks for the support btw).

> Just to be sure… you’re not using the `svgAsImage` option, are you?

I am not, unless the defaults are changed, I read the doc and `false` was declared as the default. To be clear, I am not even using a`netlify.toml`, I'm simply sticking to the defaults.

> > A thing to notice is that for now (since I'm testing it) I left a  in the head which is clearly a non-sense, can this cause issues?
> 
> If you manage to get them inlined you should probably remove that yeah!

I tried and it didn't change anything :(

> Btw you may want to consider simply using Hugo’s templating language to inline your svgs? From a quick search it seems like you can render the svg files directly as partials? Also quick warning, sometimes SVGs are so big that it may lead to worse performance to inline them.

You are totally right, I was simply using both your inlining plugins to test with tools like webpagetest.org, gtmetrix.com or lighthouse which configuration was the best one. I can consider inlining with hugo as a definitive solution for sure, but using plugins was a no-brainer to make testing faster.

**Comment by Tom-Bonnike** [comment]
Alright, I’ll do some testing/minimal reproduction case sometime soon.

**Comment by TonioGela** [comment]
Again, thank you :)
