### ISSUE TITLE
Error: Unsucessful HTTP response

### ISSUE THREAD

**Issue by ehmicky** [Tom-Bonnike/netlify-plugin-inline-source#7]
The following error is shown in some builds:

```
Inlining sources failed.
Unsuccessful HTTP response 
    /opt/buildhome/.netlify-build-plugins/node_modules/superagent/lib/node/index.js:871:15 Request.callback
    /opt/buildhome/.netlify-build-plugins/node_modules/superagent/lib/node/index.js:1114:20 IncomingMessage.<anonymous>
    events.js:322:22 IncomingMessage.emit
    _stream_readable.js:1187:12 endReadableNT
    internal/process/task_queues.js:84:21 processTicksAndRejections
```

The repository is [here](https://github.com/brenomzy/portfolio-gatsby).
The build logs do not provide any additional information unfortunately.
Do you know what the error might be? Thanks!

**Comment by Tom-Bonnike** [comment]
Meh, “unsuccessful http response” is really not an helpful error. It could be a simple network hiccup, too 🤪 

`superagent` is used by `inline-source` to load remote sources (absolute HTTP urls).
I looked at the repo and its history, but I can’t find any `inline` attribute, so I don’t see why there would be an HTTP request made. The user might have force-pushed, though.

@brenomzy could you give us more information, please? Do you remember what asset you tried to inline? I want to make sure this isn’t a problem on the plugin’s side.

**Comment by brenomzy** [comment]
Hey, Tom!

I'm sorry, I was just testing the Netlify Plugins, had no idea it would
create a issue on Github.

I actually don't have anything that I need to inline that I know of.

Thank you!

Em ter., 2 de jun. de 2020 às 05:30, Tom Bonnike <notifications@github.com>
escreveu:

**Comment by Tom-Bonnike** [comment]
Ok, that’s weird, but thanks Breno! I’ll close this issue for now, can’t really do much more about it. 🤷‍♂️
